version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sic_facerecognition_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data_gallery:/app/data_gallery
      - ./reports:/app/reports
    environment:
      - SECRET_KEY=sic_face_recognition_super_secret_jwt_key_2026
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sic_facerecognition_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
