version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: sic_postgres_db
    restart: always
    environment:
      POSTGRES_USER: sic_user
      POSTGRES_PASSWORD: sic_password_2026
      POSTGRES_DB: sic_facevit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: web/backend/Dockerfile
    container_name: sic_flask_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://sic_user:sic_password_2026@postgres_db:5432/sic_facevit_db
      SECRET_KEY: sic_facevit_super_secret_jwt_key_2026
      JWT_SECRET_KEY: sic_facevit_jwt_secret_key_2026
    ports:
      - "5000:5000"
    volumes:
      - ./outputs:/app/outputs
      - ./weights:/app/weights
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    container_name: sic_react_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
